config/routes.rb
YouMustDo::Application.routes.draw do
  
  # User & Clearance Routes
  # ==========================================================================================
  match '/sign_in', :to => 'sessions#new', :as => "sign_in"
  match '/sign_out', :to => 'sessions#destroy', :as => 'sign_out'
  match '/sign_up', :to  => 'users#new', :as => 'sign_up'
  resource  :session, :controller => 'sessions', :only => [:new, :create, :destroy]
  resources :passwords, :controller => 'passwords', :only => [:new, :create]
  resources :users, :controller => 'users', :only => [:new, :create] do
    resource :password, :controller => 'passwords', :only => [:create, :edit, :update]
    resource :confirmation, :controller => 'clearance/confirmations', :only => [:new, :create]
    member do
      get :profile
      put :update_profile
    end
  end
  
  
  # Sections Routes
  # ==========================================================================================
  root :to => 'home#index'
  match '/musts/me', :to => 'musts#my_musts', :as => 'my_musts'
  match '/u/:username', :to => 'musts#user_musts', :as => 'user_musts'
  match '/tags/:tag', :to => 'musts#tags', :as => 'tags'
  match '/recents', :to => 'musts#recents', :as => 'recents'
  match '/favorites', :to => 'favorites#index', :as => 'favorites'
  match '/bucket_list', :to => 'buckets#index', :as => 'buckets'
  match '/privacy', :to => 'home#privacy', :as => 'privacy'
  match '/terms', :to => 'home#terms', :as => 'terms'
  match '/about', :to => 'home#about', :as => 'about'


  # Musts Routes
  # ==========================================================================================
  resources :musts do
    resources :comments
    match '/agree', :to => 'agrees#agree', :as => 'agree'
    match '/disagree', :to => 'agrees#disagree', :as => 'disagree'
    match '/favorite', :to => 'favorites#favorite', :as => 'favorite'
    match '/unfavorite', :to => 'favorites#unfavorite', :as => 'unfavorite'
    match '/bucket/add', :to => 'buckets#create', :as => 'add_bucket'
    match '/bucket/done', :to => 'buckets#update', :as => 'done_bucket'
  end
  match '/musts/get_url_metadata', :to => 'musts#get_url_metadata', :as => 'get_url_metadata'


  # Follow/Unfollow
  # ==========================================================================================
  match '/followers', :to => 'follows#followers', :as => 'followers'
  match '/followings', :to => 'follows#followings', :as => 'followings'
  match '/follow/:user_id', :to => 'follows#follow', :as => 'follow'
  match '/ufollow/:user_id', :to => 'follows#unfollow', :as => 'unfollow'
  

  # Routes for social networks
  # ==========================================================================================
  # Facebook
  match '/facebook/auth', :to => 'facebook/sessions#new', :as => 'facebook_auth'
  match '/facebook/connect', :to => 'facebook/sessions#create', :as => 'facebook_connect'
  namespace :facebook do
    resource :users, :only => [:new, :create]
  end
  # Twitter
  match '/twitter/login', :to => 'twitter/sessions#create', :as => 'twitter_login'
  match '/twitter/connect', :to => 'twitter/sessions#connect', :as => 'twitter_session'
  namespace :twitter do
    resource :users, :only => [:new, :create]
  end


  # Routes for searching
  # ==========================================================================================
  resources :search, :only => [:index]
  
  
  # Routes for categories
  # ==========================================================================================
  match '/:category', :to => 'categories#show', :as => 'categories'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  acts_as_followable
  acts_as_follower
  acts_as_favorite_user
  
  has_many :musts, :dependent => :nullify
  has_many :comments, :dependent => :nullify
  has_many :buckets
  
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_uniqueness_of :email  
  validates_format_of :username, :with => /^[a-z][\w\-]+$/i, :message => "cannot contain special characters or spaces"
  validates_exclusion_of :username, :in => %w( support blog www billing help api dev test production prod staging qa stage docs samples koombea examples status account doc docs), :message => "is not available"
  validates_length_of :username, :maximum => 20
  before_save :downcase_email
  
  has_attached_file :avatar,
    :styles => {
      :tiny => "35x35",
      :preview => "175x175",
      :large => "300x300"
    }, 
    :storage => :s3,
    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
    :path => "/uploads/avatars/:attachment/:id/:style.:extension",
    :bucket => AMAZON_S3['bucket']
    
  def self.authenticate(email, password)
    user = find_by_username(email) || find_by_email(email.to_s.downcase)
    user && user.authenticated?(password) ? user : nil
  end

  def post_to_facebook(content, must_url=nil)
    feed_content = content.is_a?(Must) ? content.to_facebook_feed : content.to_s
    MustShare.post_to_facebook(self.fb_access_token, feed_content, must_url)
  end

  def post_to_twitter(content, must_url=nil)
    tweet = content.is_a?(Must) ? content.to_tweet(must_url) : content.to_s
    MustShare.post_to_twitter(self.twitter_client, tweet)
  end
  
  def bucket_list_count
    self.buckets.find(:all, :conditions => {:status => false}).count
  end

  protected
  
  def twitter_client
    oauth = Twitter::OAuth.new(TWITTER_AUTH['key'], TWITTER_AUTH['secret'])
    oauth.authorize_from_access(self.access_token, self.access_secret)

    client = Twitter::Base.new(oauth)
    client
  end
  
  def downcase_email
    self.email = self.email.downcase
  end
  

  class << self
    def random_string(len)
      # This mehotd generates a random string consisting of characters and digits
      chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
      string = ""
      1.upto(len) { |i| string << chars[rand(chars.size-1)] }
      chars = ("0".."9").to_a
      return string + chars[rand(chars.size-1)]
    end
  end
end

app/controllers/facebook/users_controller.rb
class Facebook::UsersController < ApplicationController
  layout "login"
  
  def new
    @user = User.new({
      :facebook_uid => session[:facebook_session][:facebook_uid],
      :email => session[:facebook_session][:email],
      :fb_access_token => session[:facebook_session][:fb_access_token]
    })
    flash[:success] = "You have succesfully signed in with facebook."
  end

  def create
    password = User.random_string(10)
    @user = ::User.new params[:user].update({
      :facebook_uid => session[:facebook_session][:facebook_uid],
      :email => session[:facebook_session][:email],
      :fb_access_token => session[:facebook_session][:fb_access_token],
      :password => password,
      :password_confirmation => password
    })
    @user.avatar_type = 1
    if @user.save
      @user.confirm_email!
      sign_in(@user)
      clear_facebook_session
      flash[:success] = "You have succesfully signed up with facebook."
      redirect_to root_path
    else
      flash[:error] = "Oops, please try again"
      render :action => 'new'
    end
  end

  private

  def clear_facebook_session
    session[:facebook_session]  = nil
  end
end

app/controllers/twitter/users_controller.rb
class Twitter::UsersController < ApplicationController
  before_filter :redirect_home_if_signed_in, :only => [:new, :create]
  layout "login"
  
  def new
    @user = User.new({
      :screen_name => session[:twitter_session][:screen_name],
      :username => session[:twitter_session][:screen_name]
    })
    flash[:success] = "You have succesfully logged in with twitter."
    render :template => "twitter/users/new"
    #create
  end

  def create
    find_or_create_user
    if @user.save
      @user.confirm_email!
      sign_in(@user)
      clear_twitter_cookie
      flash[:success] = "You have succesfully logged in with twitter."
      redirect_to url_after_create
    else
      flash[:error] = "Oops, please try again"
      render :template => 'twitter/users/new'
    end
  end

  private

  def clear_twitter_cookie
    session[:rtoken]  = nil
    session[:rsecret] = nil
  end

  def url_after_create
    root_path
  end

  def find_or_create_user
    password = User.random_string(10)
    @user = User.find_by_email(params[:user][:email])
    @user = ::User.new(params[:user]) if @user.nil?
    @user.avatar_type = 2
    @user.twitter_id    = session[:twitter_session][:id]
    @user.screen_name   = session[:twitter_session][:screen_name]
    @user.access_token  = session[:twitter_session][:access_token]
    @user.access_secret = session[:twitter_session][:access_secret]
    @user.avatar_url = session[:twitter_session][:avatar_url]
    @user.password = password
    @user.password_confirmation = password
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_filter :authenticate, :except => [:new, :create]
  before_filter :check_valid_user, :only => [:profile, :update]

  def new
    @user = ::User.new(params[:user])
    render :layout => "login"
  end

  def profile
    @user = User.find(params[:id])
    render :layout => "login"
  end

  def update_profile
    @user = current_user
    before_name = current_user.username
    before_email = current_user.email

    if @user.update_attributes(params[:user])
      respond_to do |format|
        flash[:success] = "Profile updated successfully."
        format.html { redirect_to user_profile_path(@user) }
      end
    else
      current_user.username = before_name
      current_user.email = before_email
      respond_to do |format|
        flash[:error] = "Error updating the profile."
        format.html { render :action => "profile" }
      end
    end
  end

end

app/helpers/facebook/users_helper.rb
module Facebook::UsersHelper
end

app/views/users/_form.html.erb
<a href="<%= twitter_login_path %>" class="login">
  <%= image_tag("buttons/btn_twitter_login.png", :alt => "Twitter login") %>
</a>
<a id="facebook_connect" href="javascript:void(0)" class="login">
  <%= image_tag("buttons/btn_facebook_connect.png", :alt => "Facebook login") %>
</a>
  <%= form.error_messages %>
  <ul>
    <li>
  <%= form.label :username %> <br/>
  <%= form.text_field :username, :class => "text" %>
</li>
<li>
  <%= form.label :email %> <br/>
  <%= form.text_field :email, :class => "text" %>
</li>
<li>
  <%= form.label :password %> <br/>
  <%= form.password_field :password, :class => "text" %>
</li>
<li>
  <%= form.label :password_confirmation, "Confirm password" %> <br/>
  <%= form.password_field :password_confirmation, :class => "text" %>
</li>
<li>

app/views/users/new.html.erb
<% title "Sign up" %>

<div id="login">
  <%= form_for @user do |form| %>
    <%= form.error_messages %>
    <ul>
      <li><h3>"Sign up" is the first thing You Must do!</h3></li>
      <li>
        <%= form.label :username %>
        <span><%= form.text_field :username, :class => "input" %></span>
      </li>
      <li>
        <%= form.label :email %>
        <span><%= form.text_field :email, :class => "input" %></span>
      </li>
      <li>
        <%= form.label :password %>
        <span><%= form.password_field :password, :class => "input" %></span>
      </li>
      <li>
        <%= form.label :password_confirmation, "Confirm password" %>
        <span><%= form.password_field :password_confirmation, :class => "input" %></span>
      </li>
      <li><%= form.submit "Sign Up", :class => "btn_login" %></li>
    </ul>
  <% end %>
</div>

app/views/users/profile.html.erb
<div id="menu_lower">
	<ul>
		<li><a href="javascript:void(0)" onclick="change_profile_tabs('info')" id="link_info" class="selected">Profile Information</a></li>
		<li><a href="javascript:void(0)" onclick="change_profile_tabs('password')" id="link_password">Change Password</a></li>
		<li><a href="javascript:void(0)" onclick="change_profile_tabs('avatar')" id="link_avatar">Change Avatar</a></li>
	</ul>
</div>

<div id="avatar" style="display:none">

	<div id="login" class="form_left">

		<%= form_for @user, :html => {:method => :put, :multipart => true}, :url => update_profile_user_path(current_user) do |form| -%>

		<%= form.error_messages %>
		<ul class="left">
			<li><h3>Change your Avatar</h3></li>
			<li>
				<% unless current_user.fb_access_token.nil? %>
				<%= facebook_avatar(current_user,50) %> 
				<input type="radio" name="user[avatar_type]" value="1">Use my Facebook Avatar
				<% end %>
			</li>

			<li>
				<% unless current_user.twitter_id.nil?%>
				<%= twitter_avatar(current_user,50) %> 
				<input type="radio" name="user[avatar_type]" value="2">Use my Twitter avatar
				<% end %>
			</li>

			<li>
				<%= gravatar_for(current_user,50) %> 
				<input type="radio" name="user[avatar_type]" value="3">Use my Gravatar
			</li>

			<li>
				<% unless current_user.external_avatar_url.blank?%>
				<%= external_url_avatar(current_user,50) %> 
				<input type="radio" name="user[avatar_type]" value="4">Use my External Location Avatar
				<% end %>
			</li>

			<li>
				<% unless current_user.avatar_file_name.nil?%>
				<%= uploaded_avatar(current_user,50) %>
				<input type="radio" name="user[avatar_type]" value="5">Use my Uploaded Avatar
				<% end %>
			</li>
			<li>
				<%= form.label :external_avatar_url, "Use New External Link image" %>
				<span><%= form.text_field :external_avatar_url, :class => "input" %></span>
			</li>

			<li>
				<%= form.label :avatar, "Upload a new Picture" %>
				<span><%= form.file_field :avatar, :class => "input" %></span>
			</li>

			<li><%= form.submit "", :class => "btn_save" %></li>
		</ul>

	</div>
	<% end -%>
</div>

<div id="info">

	<div id="login" class="form_left">
		<%= form_for @user, :html => {:method => :put}, :url => update_profile_user_path(current_user) do |form| -%>

		<%= form.error_messages %>

		<ul class="left">
			<li><h3>Update your account information</h3></li>
			<li>
				<%= form.label :username %>
				<span><%= form.text_field :username, :class => "input" %></span>
			</li>
			<li>
				<%= form.label :email %>
				<span><%= form.text_field :email, :class => "input" %></span>
			</li>
			<li>
				<%= form.label :web %>
				<span><%= form.text_field :web, :class => "input" %></span>
			</li>
			<li>
				<%= form.label :location %>
				<span><%= form.text_field :web, :class => "input" %></span>
			</li>
			<li>
				<%= form.label :bio %>
				<span><%= form.text_area :bio, :class => "input_area" %></span>
			</li>

			<li><%= form.submit "", :class => "btn_save" %></li>
		</ul>

		<% end %>
	</div>	
</div>


<div id="password" style="display:none">

	<div id="login" class="form_left">
		<%= form_for @user, :html => {:method => :put}, :url => update_profile_user_path(current_user) do |form| -%>

		<%= form.error_messages %>

		<ul class="left">
			<li><h3>Change your Password</h3></li>
			<li>
				<%= form.label :password %>
				<span><%= form.password_field :password, :class => "input" %></span>
			</li>
			<li>
				<%= form.label :password_confirmation %>
				<span><%= form.password_field :password_confirmation, :class => "input" %></span>
			</li>		

			<li><%= form.submit "", :class => "btn_save" %></li>
		</ul>

		<% end %>
	</div>	
</div>