config/routes.rb
YouMustDo::Application.routes.draw do
  
  # User & Clearance Routes
  # ==========================================================================================
  match '/sign_in', :to => 'sessions#new', :as => "sign_in"
  match '/sign_out', :to => 'sessions#destroy', :as => 'sign_out'
  match '/sign_up', :to  => 'users#new', :as => 'sign_up'
  resource  :session, :controller => 'sessions', :only => [:new, :create, :destroy]
  resources :passwords, :controller => 'passwords', :only => [:new, :create]
  resources :users, :controller => 'users', :only => [:new, :create] do
    resource :password, :controller => 'passwords', :only => [:create, :edit, :update]
    resource :confirmation, :controller => 'clearance/confirmations', :only => [:new, :create]
    member do
      get :profile
      put :update_profile
    end
  end
  
  
  # Sections Routes
  # ==========================================================================================
  root :to => 'home#index'
  match '/musts/me', :to => 'musts#my_musts', :as => 'my_musts'
  match '/u/:username', :to => 'musts#user_musts', :as => 'user_musts'
  match '/tags/:tag', :to => 'musts#tags', :as => 'tags'
  match '/recents', :to => 'musts#recents', :as => 'recents'
  match '/favorites', :to => 'favorites#index', :as => 'favorites'
  match '/bucket_list', :to => 'buckets#index', :as => 'buckets'
  match '/privacy', :to => 'home#privacy', :as => 'privacy'
  match '/terms', :to => 'home#terms', :as => 'terms'
  match '/about', :to => 'home#about', :as => 'about'


  # Musts Routes
  # ==========================================================================================
  resources :musts do
    resources :comments
    match '/agree', :to => 'agrees#agree', :as => 'agree'
    match '/disagree', :to => 'agrees#disagree', :as => 'disagree'
    match '/favorite', :to => 'favorites#favorite', :as => 'favorite'
    match '/unfavorite', :to => 'favorites#unfavorite', :as => 'unfavorite'
    match '/bucket/add', :to => 'buckets#create', :as => 'add_bucket'
    match '/bucket/done', :to => 'buckets#update', :as => 'done_bucket'
  end
  match '/musts/get_url_metadata', :to => 'musts#get_url_metadata', :as => 'get_url_metadata'


  # Follow/Unfollow
  # ==========================================================================================
  match '/followers', :to => 'follows#followers', :as => 'followers'
  match '/followings', :to => 'follows#followings', :as => 'followings'
  match '/follow/:user_id', :to => 'follows#follow', :as => 'follow'
  match '/ufollow/:user_id', :to => 'follows#unfollow', :as => 'unfollow'
  

  # Routes for social networks
  # ==========================================================================================
  # Facebook
  match '/facebook/auth', :to => 'facebook/sessions#new', :as => 'facebook_auth'
  match '/facebook/connect', :to => 'facebook/sessions#create', :as => 'facebook_connect'
  namespace :facebook do
    resource :users, :only => [:new, :create]
  end
  # Twitter
  match '/twitter/login', :to => 'twitter/sessions#create', :as => 'twitter_login'
  match '/twitter/connect', :to => 'twitter/sessions#connect', :as => 'twitter_session'
  namespace :twitter do
    resource :users, :only => [:new, :create]
  end


  # Routes for searching
  # ==========================================================================================
  resources :search, :only => [:index]
  
  
  # Routes for categories
  # ==========================================================================================
  match '/:category', :to => 'categories#show', :as => 'categories'
end

app/views/shared/_facebook_scripts.html.erb
<script type="text/javascript">
  /* <![CDATA[ */
  fb_window = null;

  jQuery(function(){
    // Facebook connect
    $("a#facebook_connect").click(function(obj) {
      if(fb_window && !fb_window.closed) {
        fb_window.focus()
      } else {
        fb_window = window.open("","holderWindow","resizable=no,width=640,height=480");
        fb_window.moveTo(screen.availWidth/2 - 320, screen.availHeight/2 -240);
        fb_window.focus();
        fb_window.location = "<%= facebook_auth_url %>";
      }
    });
  });
  /* ]]> */
</script>

app/views/shared/_flashes.html.erb
<div id="flash" style="display:none;">
	<% flash.each do |key, value| -%>
	<p class="<%= key %>"><%= image_tag("icons/#{key}.png") %><%=h value %></p>
	<% end -%>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    setTimeout("show_messages()", 200);
  });
  
  function show_messages() {
    $("#flash").fadeIn(500);
    setTimeout("hide_messages()", 5000);
  }
  
  function hide_messages() {
    $("#flash").fadeOut(500);
  }
</script>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19022287-3']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_li.html.erb
<% unless @must.nil? %>
<li style='display:none'><div class="avatar_img"><%= avatar_for(@must.user,30)%></div>
	<span><%=h @must.user.username %></span><br/>
	<span><%=h link_to @must.name, must_path(@must) %></span><br/>
	<small><%=time_ago_in_words(@must.updated_at)%> ago</small>
</li>
<script type="text/javascript">
$('#recent_must li:first').fadeIn();
</script>

<% end %>

app/views/shared/_sidebar.html.erb
<!--right panel start -->
<div id="right">
	<form id="search_form">
		<input type="text" id="search" name="search" onchange="javascript:unfinished()" value="search ...">
	</form>
		
	<p class="wordcloud">
		<%# tag_cloud(Must.tag_counts_on(:tags), %w(cloud1 cloud2 cloud3 cloud4)) do |tag, css_class| %>
		   <%#= link_to tag.name, tags_path(tag.name), :class => css_class %>
		<%# end %>
	</p>

	<h3 class='peoplemusting'>RECENT ACTIVITY </h3>
	
	<% musts_recent = Must.find(:all, :order => "created_at desc", :limit => '5')%>
	<% unless musts_recent.nil? %>
	<ul id="recent_must">
		<% musts_recent.each do |must| %>
		<li>
			<div class="avatar_content">
				<div class="avatar_img"><%= avatar_for(must.user,28)%></div>
			</div>
			<div class="avatar_content_right">
				<span><%=h must.user.username %></span><br/>
				<span><%=h link_to must.name, must_path(must) %></span><br/>
				<small><%=time_ago_in_words(must.created_at)%> ago</small>
			</div>
		</li>
		<% end %>
	</ul>
	<% else %>
		<p>There is no recent activity.</p>
	<% end %>

	<script type="text/javascript">
	$(window).load(function(){
		<% unless @date.nil?%>
		//load_more_muts("<%=@date%>")
		<% end %>
	});
	</script>
</div><!-- right -->