config/routes.rb
YouMustDo::Application.routes.draw do
  
  # User & Clearance Routes
  # ==========================================================================================
  match '/sign_in', :to => 'sessions#new', :as => "sign_in"
  match '/sign_out', :to => 'sessions#destroy', :as => 'sign_out'
  match '/sign_up', :to  => 'users#new', :as => 'sign_up'
  resource  :session, :controller => 'sessions', :only => [:new, :create, :destroy]
  resources :passwords, :controller => 'passwords', :only => [:new, :create]
  resources :users, :controller => 'users', :only => [:new, :create] do
    resource :password, :controller => 'passwords', :only => [:create, :edit, :update]
    resource :confirmation, :controller => 'clearance/confirmations', :only => [:new, :create]
    member do
      get :profile
      put :update_profile
    end
  end
  
  
  # Sections Routes
  # ==========================================================================================
  root :to => 'home#index'
  match '/musts/me', :to => 'musts#my_musts', :as => 'my_musts'
  match '/u/:username', :to => 'musts#user_musts', :as => 'user_musts'
  match '/tags/:tag', :to => 'musts#tags', :as => 'tags'
  match '/recents', :to => 'musts#recents', :as => 'recents'
  match '/favorites', :to => 'favorites#index', :as => 'favorites'
  match '/bucket_list', :to => 'buckets#index', :as => 'buckets'
  match '/privacy', :to => 'home#privacy', :as => 'privacy'
  match '/terms', :to => 'home#terms', :as => 'terms'
  match '/about', :to => 'home#about', :as => 'about'


  # Musts Routes
  # ==========================================================================================
  resources :musts do
    resources :comments
    match '/agree', :to => 'agrees#agree', :as => 'agree'
    match '/disagree', :to => 'agrees#disagree', :as => 'disagree'
    match '/favorite', :to => 'favorites#favorite', :as => 'favorite'
    match '/unfavorite', :to => 'favorites#unfavorite', :as => 'unfavorite'
    match '/bucket/add', :to => 'buckets#create', :as => 'add_bucket'
    match '/bucket/done', :to => 'buckets#update', :as => 'done_bucket'
  end
  match '/musts/get_url_metadata', :to => 'musts#get_url_metadata', :as => 'get_url_metadata'


  # Follow/Unfollow
  # ==========================================================================================
  match '/followers', :to => 'follows#followers', :as => 'followers'
  match '/followings', :to => 'follows#followings', :as => 'followings'
  match '/follow/:user_id', :to => 'follows#follow', :as => 'follow'
  match '/ufollow/:user_id', :to => 'follows#unfollow', :as => 'unfollow'
  

  # Routes for social networks
  # ==========================================================================================
  # Facebook
  match '/facebook/auth', :to => 'facebook/sessions#new', :as => 'facebook_auth'
  match '/facebook/connect', :to => 'facebook/sessions#create', :as => 'facebook_connect'
  namespace :facebook do
    resource :users, :only => [:new, :create]
  end
  # Twitter
  match '/twitter/login', :to => 'twitter/sessions#create', :as => 'twitter_login'
  match '/twitter/connect', :to => 'twitter/sessions#connect', :as => 'twitter_session'
  namespace :twitter do
    resource :users, :only => [:new, :create]
  end


  # Routes for searching
  # ==========================================================================================
  resources :search, :only => [:index]
  
  
  # Routes for categories
  # ==========================================================================================
  match '/:category', :to => 'categories#show', :as => 'categories'
end

app/views/layouts/_toptabs.html.erb
<ul id="top_menu">
	<li><a <% if (controller.controller_name == "home" && controller.action_name == "index")%> class="active" <% end %> href="<%= root_path %>">Top Musts</a></li>
	<li><a <% if (controller.controller_name == "musts" && controller.action_name == "recents")%> class="active" <% end %> href="<%= recents_path %>">Recent Musts</a></li>
	<% if signed_in? %>	
	<li><a <% if (controller.controller_name == "search" && controller.action_name == "index")%> class="active" <% end %> href="<%= search_index_path %>">People</a></li>
	<li><a <% if (controller.controller_name == "blahblah" && controller.action_name == "blahblah")%> class="active" <% end %> href="javascript:void(0)" onclick="javascript:unfinished()">Following</a></li>
	<li><a <% if (controller.controller_name == "musts" && controller.action_name == "my_musts")%> class="active" <% end %> href="<%= my_musts_path %>">My Musts</a></li>
	<li><a <% if (controller.controller_name == "buckets")%> class="active" <% end %> id="bucket_list_tab" href="<%= buckets_path %>">Bucket List<% if current_user.bucket_list_count > 0%><span><%= current_user.bucket_list_count %></span><% end %></a></li>
	<li><a <% if controller.controller_name == "favorites" %> class="active" <% end %> href="<%= favorites_path %>">Favorites</a></li>
	<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>You Must do<%= (":: " + yield(:title).to_s) unless yield(:title).blank? %></title>
	<%= stylesheet_link_tag 'reset' %>
	<%= stylesheet_link_tag 'style' %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
  <%= yield :javascript %>
</head>

<body>
  <h1><%= yield(:header).to_s unless yield(:header).blank? %></h1>
  <div id="flash">
        <% flash.each do |key, value| -%>
          <div id="flash_<%= key %>"><%=h value %></div>
        <% end -%>
      </div>
	<%= yield %>
	<% flash.discard %>

</body>

</html>

app/views/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<title>You Must do<%= (":: " + yield(:title).to_s) unless yield(:title).blank? %></title>
	<!--CSS  -->
	<%= stylesheet_link_tag 'reset' %>
	<%= stylesheet_link_tag 'global' %>
	<%= stylesheet_link_tag 'mayo' %>
	<%= stylesheet_link_tag 'bbto' %>
	<%= stylesheet_link_tag 'german' %>
	<%= yield :stylesheet %>

	<!-- Scripts -->
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= javascript_include_tag "unfinished" %>
	<%= render :partial => "shared/facebook_scripts" %>
	<%= render :partial => "shared/google_analytics" %>
	<%= yield :javascript %>
	<%= yield :additional_javascript %>
	<!--[if IE 6]>
	<script type="text/javascript"> 
	/*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; } 
	var IE6UPDATE_OPTIONS = {
	icons_path: "../javascripts/ie6update/images/"
	}
	</script>
	<script type="text/javascript" src="../javascripts/ie6update/ie6update.js"></script>
	<![endif]-->
</head>
<body class="home">

	<div id="container_big">
		<div id="wrapper">
			<div class="header">
				<div id="menu">
					<%= render :partial => 'layouts/toptabs' %>
					<ul id="user_menu">				

						<% unless signed_in? %>
						<li><a href="<%= sign_in_path %>"><span>Login</span></a></li>
						<li>
							<a id="facebook_connect" href="javascript:void(0)">
								<%= image_tag("buttons/facebook_connect.png", :alt => "Facebook") %>
							</a>
						</li>
						<li class="last">
							<a href="<%= twitter_login_path %>">
								<%= image_tag("buttons/twitter_connect.png", :alt => "Twitter") %>
							</a>
						</li>
						<% else %>
						<li>
							<%= avatar_for(current_user, 20)%>
							<a href="/users/<%=h current_user.id%>/profile"><span><%= current_user.username %></span></a>
						</li>
						<li class="last"><a class="button_twitter" href="<%= sign_out_path %>"><span>Logout</span></a></li>
						<% end %>

					</ul>
				</div>
			</div>

			<div id="yield_container">
				<div class="post">
					<%= render :partial => "shared/flashes" %>
					<%= render :partial => "shared/sidebar", :locals => {:musts => @musts_recent} %>

					<div id="left">
						<div id="header" class="home">
							<p class="postmust"><a href="/musts/new" id="postamust"></a></p>
							<h1><a href="/"><img src="/images/misc/logo.png?1287290042" alt="Logo"></a></h1>
						</div><!-- header --> 

						<div id="content">
							<ul id="must_bar">
								<li class="main"><img src="/images/misc/bar_youmust.jpg?1287290042" alt="You Must"></li>
  							<li><a href="<%=categories_path('read')%>" class="<%=link_active(@category,"Read")%>">Read</a></li>
  							<li><a href="<%=categories_path('see')%>" class="<%=link_active(@category,"See")%>">See</a></li>
  							<li><a href="<%=categories_path('watch')%>" class="<%=link_active(@category,"Watch")%>">Watch</a></li>
  							<li><a href="<%=categories_path('listen')%>" class="<%=link_active(@category,"Listen")%>">Listen</a></li>
  							<li><a href="<%=categories_path('have')%>" class="<%=link_active(@category,"Have")%>">Have</a></li>
  							<li><a href="<%=categories_path('visit')%>" class="<%=link_active(@category,"Visit")%>">Visit</a></li>
  							<li><a href="<%=categories_path('do')%>" class="<%=link_active(@category,"Do")%>">Do</a></li>	
							</ul>
							<%= yield %>
						</div><!-- content --> 
					</div>

				</div>
			</div>

		</div><!--END wrapper -->
		<br class="clear">
		<div id="footer">
				<div class="wrapper">
					<ul>
						<li><a href="<%= root_path %>">Home</a></li>
						<li><a href="<%= about_path %>">About</a></li>
						<li><a href="<%= privacy_path %>">Privacy</a></li>
						<li><a href="<%= terms_path %>">Terms</a></li>
						<li class="last"><a href="#">Contact us</a></li>
					</ul>
					<p>Developed for Rails Rumble in 48 hours</p>
				</div><!-- wrapper -->
		</div><!-- FOOTER END-->
	</div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<title>You Must do<%= (":: " + yield(:title).to_s) unless yield(:title).blank? %></title>
	<!--CSS  -->
	<%= stylesheet_link_tag 'reset' %>
	<%= stylesheet_link_tag 'global' %>
	<%= stylesheet_link_tag 'mayo' %>
	<%= stylesheet_link_tag 'bbto' %>
	<%= stylesheet_link_tag 'german' %>
	<%= yield :stylesheet %>

	<!-- Scripts -->
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= javascript_include_tag "unfinished" %>
	<%= render :partial => "shared/facebook_scripts" %>
	<%= render :partial => "shared/google_analytics" %>
	<%= yield :javascript %>
	<%= yield :additional_javascript %>
	<!--[if IE 6]>
	<script type="text/javascript"> 
	/*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; } 
	var IE6UPDATE_OPTIONS = {
	icons_path: "../javascripts/ie6update/images/"
	}
	</script>
	<script type="text/javascript" src="../javascripts/ie6update/ie6update.js"></script>
	<![endif]-->
</head>
<body>

	<div id="container_big">
		<div id="wrapper">
			<div class="header">
				<div id="menu">
					<%= render :partial => 'layouts/toptabs' %>
					<ul id="user_menu">				

						<% unless signed_in? %>
						<li><a href="<%= sign_in_path %>"><span>Login</span></a></li>
						<li>
							<a id="facebook_connect" href="javascript:void(0)">
								<%= image_tag("buttons/facebook_connect.png", :alt => "Facebook") %>
							</a>
						</li>
						<li class="last">
							<a href="<%= twitter_login_path %>">
								<%= image_tag("buttons/twitter_connect.png", :alt => "Twitter") %>
							</a>
						</li>
						<% else %>
						<li>
							<%= image_tag("misc/top_user_profile.jpg", :class => "profile", :alt => "User avatar") %>
							<a href="#"><span><%= current_user.username %></span></a>
						</li>
						<li class="last"><a class="button_twitter" href="<%= sign_out_path %>"><span>Logout</span></a></li>
						<% end %>

					</ul>
				</div>
			</div>

			<div id="yield_container">
				<div class="post">
					<%= render :partial => "shared/flashes" %>
					<%= render :partial => "shared/sidebar", :locals => {:musts => @musts_recent} %>

					<div id="left">
						<div id="header">
							<p><a href="<%=sign_up_path%>" id="sign_up"></a></p>
							<h1><a href="/"><img src="/images/misc/logo.png?1287290042" alt="Logo"></a></h1>
							<h2>You Must try this site, here you will be able to post all kind of things that you consider everyone must do. </h2>
						</div><!-- header --> 

						<div id="content">
							<ul id="must_bar">
								<li class="main"><img src="/images/misc/bar_youmust.jpg?1287290042" alt="You Must"></li>
								<li><a href="<%=categories_path('read')%>" class="<%=link_active(@category,"Read")%>">Read</a></li>
								<li><a href="<%=categories_path('see')%>" class="<%=link_active(@category,"See")%>">See</a></li>
								<li><a href="<%=categories_path('watch')%>" class="<%=link_active(@category,"Watch")%>">Watch</a></li>
								<li><a href="<%=categories_path('listen')%>" class="<%=link_active(@category,"Listen")%>">Listen</a></li>
								<li><a href="<%=categories_path('have')%>" class="<%=link_active(@category,"Have")%>">Have</a></li>
								<li><a href="<%=categories_path('visit')%>" class="<%=link_active(@category,"Visit")%>">Visit</a></li>
								<li><a href="<%=categories_path('do')%>" class="<%=link_active(@category,"Do")%>">Do</a></li>
							</ul>
							<%= yield %>
						</div><!-- content --> 
					</div>

				</div>
			</div>

		</div><!--END wrapper -->
		<br class="clear">
		<div id="footer">
			<div id="footer">
				<div class="wrapper">
					<ul>
						<li><a href="<%= root_path %>">Home</a></li>
						<li><a href="<%= about_path %>">About</a></li>
						<li><a href="<%= privacy_path %>">Privacy</a></li>
						<li><a href="<%= terms_path %>">Terms</a></li>
						<li class="last"><a href="#">Contact us</a></li>
					</ul>
					<p>Developed for Rails Rumble in 48 hours</p>
				</div><!-- wrapper -->
			</div><!-- footer -->
		</div><!-- FOOTER END-->
	</div>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<title>You Must do<%= (" :: " + yield(:title).to_s) unless yield(:title).blank? %></title>
	<!--CSS  -->
	<%= stylesheet_link_tag 'reset' %>
	<%= stylesheet_link_tag 'global' %>
	<%= stylesheet_link_tag 'mayo' %>
	<%= stylesheet_link_tag 'bbto' %>
	<%= stylesheet_link_tag 'german' %>
	<%= yield :stylesheet %>

	<!-- Scripts -->
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= javascript_include_tag "unfinished" %>
	<%= render :partial => "shared/facebook_scripts" %>
	<%= render :partial => "shared/google_analytics" %>
	<%= yield :javascript %>
	<%= yield :additional_javascript %>
	<!--[if IE 6]>
	<script type="text/javascript"> 
	/*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; } 
	var IE6UPDATE_OPTIONS = {
	icons_path: "../javascripts/ie6update/images/"
	}
	</script>
	<script type="text/javascript" src="../javascripts/ie6update/ie6update.js"></script>
	<![endif]-->
</head>
<body class="home">

	<div id="wrapper">
		<div id="menu">
			<%= render :partial => 'layouts/toptabs' %>
			<ul id="user_menu">				
				<% unless signed_in? %>
				<li><a href="<%= sign_in_path %>"><span>Login</span></a></li>
				<li>
					<a id="facebook_connect" href="javascript:void(0)">
						<%= image_tag("buttons/facebook_connect.png", :alt => "Facebook") %>
					</a>
				</li>
				<li class="last">
					<a href="<%= twitter_login_path %>">
						<%= image_tag("buttons/twitter_connect.png", :alt => "Twitter") %>
					</a>
				</li>
				<% else %>
				<li>
					<%= avatar_for(current_user, 20)%>
					<a href="/users/<%=h current_user.id%>/profile"><span><%= current_user.username %></span></a>
				</li>
				<li class="last"><a href="<%= sign_out_path %>"><span>Logout</span></a></li>
				<% end %>
			</ul>
		</div>	<!-- menu -->	
		<div id="header" class="home">
			<h1><a href="<%= root_path %>"><%= image_tag("misc/logo.png", :alt => "Logo") %></a></h1>
		</div><!-- header --> 
		<div id="content">
			<br class="fclear" />
			<%= render :partial => "shared/flashes" %>
			<%= yield %>
			<% flash.discard %>
		</div><!-- content --> 
	</div><!-- wrapper --> 
	<div id="footer_login">
		<div class="wrapper">
			<ul>
				<li><a href="<%= root_path %>">Home</a></li>
				<li><a href="<%= about_path %>">About</a></li>
				<li><a href="<%= privacy_path %>">Privacy</a></li>
				<li><a href="<%= terms_path %>">Terms</a></li>
				<li class="last"><a href="#">Contact us</a></li>
			</ul>
			<p>Developed for Rails Rumble in 48 hours</p>
		</div><!-- wrapper -->
	</div><!-- footer -->

	<!-- pngfix script -->
	<script src="/javascripts/pngfix.js" type="text/javascript"></script>
</body>
</html>

app/views/layouts/must.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<<<<<<< HEAD
	<title>You Must do<%= (":: " + yield(:title).to_s) unless yield(:title).blank? %></title>
	<!--CSS  -->
	<%= stylesheet_link_tag 'reset' %>
	<%= stylesheet_link_tag 'global' %>
	<%= stylesheet_link_tag 'mayo' %>
	<%= stylesheet_link_tag 'bbto' %>
	<%= stylesheet_link_tag 'german' %>
	<%= yield :stylesheet %>

	<!-- Scripts -->
	<%= javascript_include_tag :defaults %>
	<%= render :partial => "shared/facebook_scripts" %>
	<%= yield :javascript %>
	<%= yield :additional_javascript %>
	<!--[if IE 6]>
	<script type="text/javascript"> 
	/*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; } 
	var IE6UPDATE_OPTIONS = {
	icons_path: "../javascripts/ie6update/images/"
	}
	</script>
	<script type="text/javascript" src="../javascripts/ie6update/ie6update.js"></script>
	<![endif]-->
</head>
<body>
	<div class="container_big">
=======
    <title>You Must do<%= (" :: " + yield(:title).to_s) unless yield(:title).blank? %></title>
		<!--CSS  -->
    <%= stylesheet_link_tag 'reset' %>
    <%= stylesheet_link_tag 'global' %>
    <%= stylesheet_link_tag 'mayo' %>
    <%= stylesheet_link_tag 'bbto' %>
    <%= stylesheet_link_tag 'german' %>
    <%= yield :stylesheet %>
>>>>>>> 270a45cd2b1bf04c3f9abe21b1b7771d7ff6dfb9

		<div class="wrapper">
			<div id="menu">
				<ul id="top_menu">
					<li><a href="#">Top Musts</a></li>
					<li><a href="<%= recents_path %>">Recent Musts</a></li>
					<li><a href="#">Following</a></li>
					<li><a href="#">My Musts</a></li>
					<li><a href="#">Bucket List<span>3</span></a></li>
				</ul>
				<ul id="user_menu">				
					<% unless signed_in? %>
					<li><a href="<%= sign_in_path %>"><span>Login</span></a></li>
					<li>
						<a id="facebook_connect" href="javascript:void(0)">
							<%= image_tag("buttons/facebook_connect.png", :alt => "Facebook") %>
						</a>
					</li>
					<li class="last">
						<a href="<%= twitter_login_path %>">
							<%= image_tag("buttons/twitter_connect.png", :alt => "Twitter") %>
						</a>
					</li>
					<% else %>
					<li>
						<%= image_tag("misc/top_user_profile.jpg", :class => "profile", :alt => "User avatar") %>
						<a href="#"><span><%= current_user.username %></span></a>
					</li>
					<li class="last"><a href="<%= sign_out_path %>"><span>Logout</span></a></li>
					<% end %>
				</ul>
			</div>	<!-- menu -->	

			<div id="container">
				<%= render :partial => "shared/sidebar", :locals => {:musts => @musts_recent} %>

				<div id="left">
<<<<<<< HEAD
					<div id="header">
						<p><a id="sign_up" href=""></a></p>
						<h1><a href="<%= root_path %>"><%= image_tag("misc/logo.png", :alt => "Logo") %></a></h1>
						<h2>You Must try this site, here you will be able to post all kind of things that you consider everyone must do. </h2>
					</div><!-- header --> 
=======
				  <div id="header">
						<p><a id="sign_up" href="<%= sign_up_path %>"></a></p>
					  <h1><a href="<%= root_path %>"><%= image_tag("misc/logo.png", :alt => "Logo") %></a></h1>
					  <h2>You Must try this site, here you will be able to post all kind of things that you consider everyone must do. </h2>
				  </div><!-- header --> 
>>>>>>> 270a45cd2b1bf04c3f9abe21b1b7771d7ff6dfb9

					<div id="content">
						<div id="flash">
							<% flash.each do |key, value| -%>
							<div id="flash_<%= key %>"><%=h value %></div>
							<% end -%>
						</div>
						<ul id="must_bar">
							<li class="main"><%= image_tag("misc/bar_youmust.jpg", :alt => "You Must") %></li>
							<li><a href="<%=categories_path('read')%>" class="<%=link_active(@category,"Read")%>">Read</a></li>
							<li><a href="<%=categories_path('see')%>" class="<%=link_active(@category,"See")%>">See</a></li>
							<li><a href="<%=categories_path('watch')%>" class="<%=link_active(@category,"Watch")%>">Watch</a></li>
							<li><a href="<%=categories_path('listen')%>" class="<%=link_active(@category,"Listen")%>">Listen</a></li>
							<li><a href="<%=categories_path('have')%>" class="<%=link_active(@category,"Have")%>">Have</a></li>
							<li><a href="<%=categories_path('play')%>" class="<%=link_active(@category,"Play")%>">Play</a></li>
							<li><a href="<%=categories_path('do')%>" class="<%=link_active(@category,"Do")%>">Do</a></li>			
						</ul>
						<%= yield %>
						<% flash.discard %>
					</div><!-- content --> 
				</div> <!-- left -->	
			</div><!-- container --> 
		</div><!-- wrapper --> 
		<br class="clear" />
		<div id="footer">
			<div class="wrapper">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">About</a></li>
					<li class="last"><a href="#">Contact us</a></li>
				</ul>
				<p>Developed for Rails Rumble in 48 hours</p>
			</div><!-- wrapper -->
		</div><!-- footer -->

		<!-- pngfix script -->
		<script src="/javascripts/pngfix.js" type="text/javascript"></script>


	</div><!-- container big -->


</body>
</html>