config/routes.rb
YouMustDo::Application.routes.draw do
  
  # User & Clearance Routes
  # ==========================================================================================
  match '/sign_in', :to => 'sessions#new', :as => "sign_in"
  match '/sign_out', :to => 'sessions#destroy', :as => 'sign_out'
  match '/sign_up', :to  => 'users#new', :as => 'sign_up'
  resource  :session, :controller => 'sessions', :only => [:new, :create, :destroy]
  resources :passwords, :controller => 'passwords', :only => [:new, :create]
  resources :users, :controller => 'users', :only => [:new, :create] do
    resource :password, :controller => 'passwords', :only => [:create, :edit, :update]
    resource :confirmation, :controller => 'clearance/confirmations', :only => [:new, :create]
    member do
      get :profile
      put :update_profile
    end
  end
  
  
  # Sections Routes
  # ==========================================================================================
  root :to => 'home#index'
  match '/musts/me', :to => 'musts#my_musts', :as => 'my_musts'
  match '/u/:username', :to => 'musts#user_musts', :as => 'user_musts'
  match '/tags/:tag', :to => 'musts#tags', :as => 'tags'
  match '/recents', :to => 'musts#recents', :as => 'recents'
  match '/favorites', :to => 'favorites#index', :as => 'favorites'
  match '/bucket_list', :to => 'buckets#index', :as => 'buckets'
  match '/privacy', :to => 'home#privacy', :as => 'privacy'
  match '/terms', :to => 'home#terms', :as => 'terms'
  match '/about', :to => 'home#about', :as => 'about'


  # Musts Routes
  # ==========================================================================================
  resources :musts do
    resources :comments
    match '/agree', :to => 'agrees#agree', :as => 'agree'
    match '/disagree', :to => 'agrees#disagree', :as => 'disagree'
    match '/favorite', :to => 'favorites#favorite', :as => 'favorite'
    match '/unfavorite', :to => 'favorites#unfavorite', :as => 'unfavorite'
    match '/bucket/add', :to => 'buckets#create', :as => 'add_bucket'
    match '/bucket/done', :to => 'buckets#update', :as => 'done_bucket'
  end
  match '/musts/get_url_metadata', :to => 'musts#get_url_metadata', :as => 'get_url_metadata'


  # Follow/Unfollow
  # ==========================================================================================
  match '/followers', :to => 'follows#followers', :as => 'followers'
  match '/followings', :to => 'follows#followings', :as => 'followings'
  match '/follow/:user_id', :to => 'follows#follow', :as => 'follow'
  match '/ufollow/:user_id', :to => 'follows#unfollow', :as => 'unfollow'
  

  # Routes for social networks
  # ==========================================================================================
  # Facebook
  match '/facebook/auth', :to => 'facebook/sessions#new', :as => 'facebook_auth'
  match '/facebook/connect', :to => 'facebook/sessions#create', :as => 'facebook_connect'
  namespace :facebook do
    resource :users, :only => [:new, :create]
  end
  # Twitter
  match '/twitter/login', :to => 'twitter/sessions#create', :as => 'twitter_login'
  match '/twitter/connect', :to => 'twitter/sessions#connect', :as => 'twitter_session'
  namespace :twitter do
    resource :users, :only => [:new, :create]
  end


  # Routes for searching
  # ==========================================================================================
  resources :search, :only => [:index]
  
  
  # Routes for categories
  # ==========================================================================================
  match '/:category', :to => 'categories#show', :as => 'categories'
end

app/models/must.rb
class Must < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  acts_as_favorite
  acts_as_taggable

  validates_presence_of :name

  belongs_to :user
  belongs_to :category

  has_one :attachment, :dependent => :destroy

  has_many :comments, :dependent => :destroy
  has_many :agrees, :dependent => :destroy

  after_create :agree_must
  scope :by_creation_date, :order => "created_at DESC"

  def calification
    (self.total_agrees - self.total_disagrees).to_i
  end

  def total_agrees
    self.agrees.sum(:calification, :conditions => ['calification = ?', 1]).to_i
  end

  def total_disagrees
    self.agrees.sum(:calification, :conditions => ['calification = ?', -1]).to_i
  end

  def agree_must
    agree = Agree.create(:must_id => self.id, :user_id => self.user.id, :calification => 1)
  end

  def location
    return self.latitude + " - " + self.longitude unless self.latitude.nil? or self.longitude.nil?
    return ""
  end
  
  def is_done(u)
      if u
        bucket = Bucket.find_by_user_id_and_must_id(u.id, self.id)
        unless bucket.nil?
          return bucket.status
        else
          return false
        end
      else
        return false
      end
  end

  def category_name
    self.category.name
  end

  def to_facebook_feed
    "You Must #{category_name}: #{self.name} at YouMustDo. #{short_url}"
  end

  def to_tweet(must_url)
    short_url = UrlShortener.shorten(must_url)
    tweet = truncate("You Must #{category_name}: #{self.name}", :length => (139 - short_url.to_s.length))
    "#{tweet} #{short_url}"
  end

  # Methods to determine the category of the must
  def listen?
    self.category.name.downcase.eql?("listen")
  end
  # =============================================

  class << self
    def refresh_top_musts
      # Must.all( :select => "*, DATEDIFF(NOW(), created_at) as top_factor",
      #           :conditions => ["created_at >= ?", Time.now - 7.days])

      # Let's find the top rated Musts
      top_factor_query = %{SELECT *, DATEDIFF(NOW(), created_at) AS top_factor FROM agrees WHERE created_at >= ?}
      top_musts = Agree.find_by_sql([%{
        SELECT must_id, COUNT(id) * ((7 - top_factor) / 7) AS top_value
        FROM (#{top_factor_query}) as top_factors
        GROUP BY must_id}, Time.now - 7.days])
        
      logger.info top_musts.inspect
      puts top_musts.inspect

      # Then we reset the previous Musts top rated
      Must.update_all ["top = ?", false], ["top = ?", true]

      # And finally, we update the top rated Musts and set their new top value
      top_musts.each do |must|
        Must.find_by_id(must.must_id).update_attributes({
          :top_value => must.top_value,
          :top => true
          })
      end
    end
  end

  def should_process
    zencoder_process_audio if listen?
  end

  def attachment_format1_ready?
    response = Zencoder::Output.progress(self.attachment.format1_id)
    data = response.body.to_hash
    logger.info response.inspect
    puts response.inspect
    data['state'].to_s.eql?("finished")
  end

  def attachment_format2_ready?
    response = Zencoder::Output.progress(self.attachment.format2_id)
    data = response.body.to_hash
    logger.info response.inspect
    puts response.inspect
    data['state'].to_s.eql?("finished")
  end

  def zencoder_file_url(filename, ext)
    "s3://files.youmustdo.local/#{filename}.#{ext}"
  end

  def zencoder_process_audio
    self.reload
    response = Zencoder::Job.create({
      :input => self.attachment.file.url,
      :outputs => [
        {
          :label => zencoder_output_name("ogg"),
          :url => zencoder_file_url(zencoder_output_name, "ogg"),
          :audio_codec => "vorbis",
          :public => 1
        },
        {
          :label => zencoder_output_name("mp3"),
          :url => zencoder_file_url(zencoder_output_name, "mp3"),
          :audio_codec => "mp3",
          :public => 1
        }
      ]
    })
    data = response.body.to_hash
    self.attachment.update_attributes({
      :job_id => data['id'],
      :format1_id => data['outputs'][0]['id'],
      :format1_url => data['outputs'][0]['url'],
      :format1_label => data['outputs'][0]['label'],
      :format2_id => data['outputs'][1]['id'],
      :format2_url => data['outputs'][1]['url'],
      :format2_label => data['outputs'][1]['label']
    })
    logger.info response.inspect
    puts response.inspect
  end

  def zencoder_output_name(type="")
    "Must_#{self.id}_Attachment_#{self.attachment.id}_#{type}"
  end
end

app/controllers/musts_controller.rb
class MustsController < ApplicationController
  include ApplicationHelper

  before_filter :login_required, :only => [:create, :new, :edit, :update, :destroy]
  protect_from_forgery :except => :get_url_metadata
  layout :get_layout
  
  def recents
    @musts = Must.paginate :page => params[:page], :per_page => 20, :order => 'created_at DESC'
  end
  
  def tags
    @musts = Must.tagged_with(params[:tag]).by_creation_date.paginate(:page => params[:page], :per_page => 20)
    @tag = params[:tag]
  end
  
  def my_musts
    @musts = current_user.musts.paginate :page => params[:page], :per_page => 20, :order => 'created_at DESC'
  end

  def play
  end
  
  def user_musts
    @user = User.find_by_username(params[:username])
    @musts = @user.musts.paginate :page => params[:page], :per_page => 20, :order => 'created_at DESC'
  end

  def new
    @user = current_user
    @must = Must.new(params[:must])
    @must.category_id = params[:category] if params[:category]
    render :layout => 'login'
  end

  def load_more
    @must = Must.last
    @update = true if last_must = @must.created_at > Time.parse(params[:date])
    respond_to do |wants|
      wants.js
    end
  end

  def create
    @must = Must.new(params[:must])
    if params[:attachment]
      @must.build_attachment(params[:attachment]) unless params[:attachment][:file].blank?
    end
    @must.user = current_user
    if @must.save
      @must.should_process #Process attachments
      current_user.post_to_facebook(@must, must_url(@must)) if params[:share][:facebook].eql?("1")
      current_user.post_to_twitter(@must, must_url(@must)) if params[:share][:twitter].eql?("1")
      flash[:notice] = "Awesome, one more thing they must do!"
      respond_to do |wants|
        wants.html { redirect_to must_path(@must) }
      end
    else
      flash[:error] = "Ouch sorry, Something's not right down there, please verify your information and try again."
      respond_to do |wants|
        wants.html { render :action => "new" }
      end
    end
  end


  def show
    @comment = Comment.new
    @must = Must.find(params[:id])
    render :action => "show"
  end

  def destroy
    @must = Must.find(params[:id])
    if @must.destroy
      flash[:notice] = "Must deleted"
      redirect_to musts_path
    else
      flash[:error] = "Ouch sorry, Something's not right down there, please verify your information and try again."
      render :action => "new"
    end
  end

  def get_url_metadata
    if params[:url]
      data = Metadata.get(params[:url])
      @title = data[0]
      @description = data[1]
      @images      = data[2]
      @videos      = {:url => data[4], :type => data[3]}
      respond_to do |wants|
        wants.js
      end
    end
  end

end

app/helpers/must_helper.rb
module MustHelper
  
  def show_content(must)
    unless must.url_video.nil?
      return video(must.url_video)
    end
    unless must.url_image.nil?
      return '<img src="'+must.url_image+'" class="most_image" alt="'+must.name+'" />' 
    end
    unless must.longitude.blank? or must.latitude.blank?
      return return_map(must)
    end
    return image_tag('YouMustDoTwitter watermark.jpg')
  end
    
  def show_big_content(must)
    unless must.url_video.nil?
      return bgvideo(must.url_video)
    end
    unless must.url_image.nil?
      return '<img src="'+must.url_image+'" id="bg_most_image" alt="'+must.name+'" />' 
    end
    unless must.longitude.blank? or must.latitude.blank?
      return bgreturn_map(must)
    end
    puts image_tag('YouMustDoTwitter watermark.jpg')
    return image_tag('YouMustDoTwitter watermark.jpg')
  end

  def video(url)
    if url =~ /(youtube.com)/
      return '  <object width="150" height="100"><param name="movie" value="'+url+'"></param><param name="allowFullScreen"     value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="'+url+'" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="150" height="100"></embed></object>'
    end
    if url =~ /(vimeo.com)/
      return '<iframe src="'+url+'" width="150" height="100" frameborder="0"></iframe>'
    end
    if url =~ /(dailymotion.com)/
      return '<object width="150" height="100"><param name="movie" value="'+url+'"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed type="application/x-shockwave-flash" src="'+url+'" width="480" height="270" allowfullscreen="true" allowscriptaccess="always"></embed></object>'
    end
  end
  
  def bgvideo(url)
    if url =~ /(youtube.com)/
      return '  <object width="300" height="208"><param name="movie" value="'+url+'"></param><param name="allowFullScreen"     value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="'+url+'" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300" height="208"></embed></object>'
    end
    if url =~ /(vimeo.com)/
      return '<iframe src="'+url+'" width="300" height="208" frameborder="0"></iframe>'
    end
    if url =~ /(dailymotion.com)/
      return '<object width="300" height="208"><param name="movie" value="'+url+'"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed type="application/x-shockwave-flash" src="'+url+'" width="300" height="208" allowfullscreen="true" allowscriptaccess="always"></embed></object>'
    end
  end
  
  def return_map(must)
    return '<img src="http://maps.google.com/maps/api/staticmap?center='+must.latitude+', '+must.longitude+'&amp;zoom=11&amp;size=150x100&amp;maptype=roadmap&amp;sensor=false&amp;markers=color:blue|label:1|'+must.latitude+','+must.longitude+'" alt="Location">'
  end
  
  def bgreturn_map(must)
    return '<img src="http://maps.google.com/maps/api/staticmap?center='+must.latitude+', '+must.longitude+'&amp;zoom=11&amp;size=150x100&amp;maptype=roadmap&amp;sensor=false&amp;markers=color:blue|label:1|'+must.latitude+','+must.longitude+'" alt="Location">'
  end

end

app/views/musts/_agrees.html.erb
<%= link_to "(+)", must_agree_path(must) %> (<%= must.total_agrees%>) <%= link_to "(-)", must_disagree_path(must)%> 

app/views/musts/_carousel.html.erb
<div id="slider1">
	<a class="buttons prev" href="#">left</a>
	<div class="viewport">
		<ul class="overview">
		  <% elem = nil %>
		  <% images.each do |image|%>
		    <% #REMOVE THIS SHIT!!! %>
		    <% elem = image.to_s if elem.nil?%>
			  <li class="pagenum"><img src="<%=image.to_s%>" /></li>
			<%end%>
		</ul>
	</div>
	<a class="buttons next" href="#">right</a>
</div>
<input type="hidden" value= "<%=elem unless elem.nil?%>" name="must[url_image]" id="must_url_image" />

app/views/musts/_comments.html.erb
<%= form_for([@must, @comment], :html => {:method => :post, :id => "comment_form"}) do |f| %>
<ul>
	<li>
		<%= f.text_area :content %>
		<%= error_message_on :comment,:description %>
	</li>
	
	<li><input type="submit" id="btn_comment" value="" /></li>	
	</u>
<% end %>

app/views/musts/_comments_list.html.erb
<% unless @must.comments.empty? %>
	<% @must.comments.each do |comment| %>
<div class="comment">	<span><%=avatar_for(comment.user,40)%><small><%=link_to comment.user.username ,user_path( comment.must.user)%></small><small><%=time_ago_in_words(comment.created_at)%> <br /> ago</small></span>
<p><%=auto_link(simple_format(comment.content), :urls, :target => "_blank")%></p>
</div> <!-- comment -->
  <%end%>
<%end%>

app/views/musts/_must_item.html.erb
  <li id='must<%= must.id%>'>
 	  <div class="left">
	      <%= link_to "", must_agree_path(must), :remote => true, :class => "add" -%>
          <span class="add_count" id="agrees_count_<%=must.id%>"><%= must.total_agrees %></span>
		  <%= link_to "", must_disagree_path(must), :remote => true, :class => "remove" -%>
		  <span class="remove_count" id="disagrees_count_<%=must.id%>"><%= must.total_disagrees %></span>
		<% if controller.controller_name == "buckets"%>  
			<%= link_to "", must_done_bucket_path(must), :remote => true, :class => "done_button" -%>
		<% end %>
		</div><!-- left -->
    <div class="<% if must.is_done(current_user)%>right done<% else %>right <% end %>">
      <ul class="icons">
				<span id="favorite_<%=must.id%>">
					<%= render :partial => "musts/favorite", :locals => {:must => must} %>
				</span>
				
				<% if current_user && controller.controller_name != "buckets"%>
					<li><%= link_to "", must_add_bucket_path(must), :remote => true, :class => "bucket_add" -%></li>
				<% end %>
				
				<li><a class="facebook" href="javascript:void(0);" title="" onclick="window.open('http://www.facebook.com/sharer.php?u=<%= must_url(must)%>&t=<%= must.name %>', 'Share this on Facebook', 'width=540,height=480');"></a></li>
				<li><a class="twitter" href="javascript:void(0);" title="" onclick="window.open('http://twitter.com/share?url=<%= must_url(must)%>&text=<%= CGI.escape(must.name) %>&via=you_must_do', 'Share this on Twitter', 'width=540,height=480');"></a></li>
      </ul>
      <div class="title"><%= avatar_for(must.user,30) %>
        <span>You must <%= must.category_name %></span> 
		<%=link_to must.name, must_path(must) %> <small>by <%=h link_to must.user.username, user_musts_path(must.user.username) %></small>
      </div><!-- title -->
      
      <div class="must_content">
		<% if true %>
        <%=raw(show_content(must))%>
		<% end %>
        <p><%=auto_link(simple_format(must.description), :urls, :target => "_blank")%></p>
		<% unless must.tag_list.blank?%>
        	<p>
			<b>Tags:</b>
	 		<% must.tag_list.each do |tag|%>
				<a href="<%= tags_path(tag) %>"><%= tag %></a>
			<% end %>
			</p>
		<% end %>
		
        <p>This must has <a href="<%= must_path(must) %>#comments"><%= pluralize(must.comments.count, 'comment') %></a></p>        
      </div> <!-- must_content -->
      <div class="related">
        
      </div>
    </div><!-- right -->
  </li>

app/views/musts/_videos.html.erb
<%if videos[:type] == "youtube"%>
  <object width="250" height="200"><param name="movie" value="<%=videos[:url]%>"></param><param name="allowFullScreen"     value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="<%=videos[:url]%>" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="150" height="100"></embed></object>
<%end%>

<%if videos[:type] == "vimeo"%>
<iframe src="<%=videos[:url]%>" width="250" height="200" frameborder="0"></iframe>
<%end%>
<%if videos[:type] == "dailymotion"%>
<object width="250" height="200"><param name="movie" value="<%=videos[:url]%>"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed type="application/x-shockwave-flash" src="<%=videos[:url]%>" width="480" height="270" allowfullscreen="true" allowscriptaccess="always"></embed></object>
<%end%>
<input type="hidden" value= "<%=videos[:url]%>" name="must[url_video]" id="must_url_video" />

app/views/musts/edit.html.erb
<%= form_for(@must, :html => {:method => :put}) do |f| %>

	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name%>
		<%= error_message_on :must,:name%>
	</p>
	
	<p>
		<%= f.label :description %><br />
		<%= f.text_area :description %>
		<%= error_message_on :must,:description %>
	</p>
	
	<p>
		<%= f.label :location %><br />
		<%= f.text_field :location%>
		<%= error_message_on :must,:location %>
	</p>
	
	<%= submit_or_cancel(f, 'Cancel') %>	
	
<% end %>

app/views/musts/get_url_metadata.js.erb
$('#must_name').val('<%= escape_javascript(@title) %>');
$('#must_description').val('<%= escape_javascript(@description) %>');
$('#external_images').html('');
$('#external_images').append("<%= escape_javascript(render(:partial => 'carousel', :locals => {:images => @images}))%>");
$('#external_videos').html('');
$('#external_videos').append("<%= escape_javascript(render(:partial => 'videos', :locals => {:videos => @videos}))%>");
var carousel = $('#slider1').tinycarousel({ pager: true});

app/views/musts/my_musts.html.erb
<% unless @musts.blank? %>
<h3>These are your Musts</h3>
	
<ul class="musts">
  <% @musts.each do |must| %>
  	<%= render :partial => "musts/must_item", :locals => {:must => must} %>
  <% end %>
</ul>
<%= will_paginate @musts %>
<% else %>
<h3>You haven't written any Must yet</h3>
<% end %>

app/views/musts/play.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'audio_js/audio-js' %>
  <%= stylesheet_link_tag 'audio_js/skins/hu.css' %>
  <%= stylesheet_link_tag 'audio_js/skins/tube.css' %>
  <%= stylesheet_link_tag 'audio_js/skins/vim.css' %>
<% end %>

<% content_for :javascript do %>
  <%= javascript_include_tag "audio" %>
  <script type="text/javascript" charset="utf-8">
    // Run the script on page load.

    // If using jQuery
    $(function(){
      AudioJS.setup();
    })

    // If using Prototype
    // document.observe("dom:loaded", function() {
    //   AudioJS.setup();
    // });

    // If not using a JS library
    // window.onload = function(){
    //   AudioJS.setup();
    // }
  </script>
<% end %>

<div>

  <!-- Begin AudioJS -->
  <div class="audio-js-box tube-css">
    <!-- Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody -->
    <audio class="audio-js" controls preload>
      <source src="http://files.youmustdo.local.s3.amazonaws.com/upload2.mp3">
    </audio>
  </div>
  <!-- End AudioJS -->

  <!-- Begin AudioJS -->
  <div class="audio-js-box vim-css">
    <!-- Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody -->
    <audio class="audio-js" controls preload>
      <source src="http://files.youmustdo.local.s3.amazonaws.com/upload2.mp3">
    </audio>
  </div>
  <!-- End AudioJS -->
  
    <!-- Begin AudioJS -->
  <div class="audio-js-box hu-css">
    <!-- Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody -->
    <audio class="audio-js" controls preload>
      <source src="http://files.youmustdo.local.s3.amazonaws.com/upload2.mp3">
    </audio>
  </div>
  <!-- End AudioJS -->
  
    <!-- Begin AudioJS -->
  <div class="audio-js-box">
    <!-- Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody -->
    <audio class="audio-js" controls preload>
      <source src="http://files.youmustdo.local.s3.amazonaws.com/upload2.mp3">
    </audio>
  </div>
  <!-- End AudioJS -->

</div>

app/views/musts/show.html.erb
<ul class="musts must">
	
		  <li id='must<%= @must.id%>'>
		 	  <div class="left">
			      <%= link_to "", must_agree_path(@must), :remote => true, :class => "add" -%>
		          <span class="add_count" id="agrees_count_<%=@must.id%>"><%= @must.total_agrees %></span>
				  <%= link_to "", must_disagree_path(@must), :remote => true, :class => "remove" -%>
				  <span class="remove_count" id="disagrees_count_<%=@must.id%>"><%= @must.total_disagrees %></span>
				<% if controller.controller_name == "buckets"%>  
					<%= link_to "", must_done_bucket_path(@must), :remote => true, :class => "done_button" %>
				<% end %>
				</div><!-- left -->
		    <div class="<% if @must.is_done(current_user)%>right done<% else %>right <% end %>">
		      <ul class="icons">
						<span id="favorite_<%=@must.id%>">
						<%= render :partial => "musts/favorite", :locals => {:must => @must} %>
						</span>

						<% if current_user && controller.controller_name != "buckets"%>
							<li><%= link_to "", must_add_bucket_path(@must), :remote => true, :class => "bucket_add" %></li>
						<% end %>

						<li><a class="facebook" href="javascript:void(0);" title="" onclick="window.open('http://www.facebook.com/sharer.php?u=<%= must_url(@must)%>&t=<%= @must.name %>', 'Share this on Facebook', 'width=540,height=480');"></a></li>
						<li><a class="twitter" href="javascript:void(0);" title="" onclick="window.open('http://twitter.com/share?url=<%= must_url(@must)%>&text=<%= CGI.escape(@must.name) %>&via=you_must_do', 'Share this on Twitter', 'width=540,height=480');"></a></li>
		      </ul>
		      <div class="title"><%= avatar_for(@must.user,30) %>
		        <span>You must <%= @must.category_name %></span> 
				<%= link_to @must.name, must_path(@must) %> <small>by <%= link_to @must.user.username, user_musts_path(@must.user.username) %></small>
		      </div><!-- title -->

<div class="must_content">
<% if @must.listen? %>
  <!-- Begin AudioJS -->
  <div class="audio-js-box">
    <!-- Using the Audio for Everybody Embed Code http://camendesign.com/code/audio_for_everybody -->
    <audio class="audio-js" controls preload>
      <source src="<%= @must.attachment.format1_url %>">
      <source src="<%= @must.attachment.format2_url %>">
    </audio>
  </div>
  <!-- End AudioJS -->
<% else %>
  <%=raw(show_big_content(@must))%>
<% end %>

<p><%= auto_link(simple_format(@must.description), :urls, :target => "_blank") %><br/><%= link_to("#{@must.category_name} more...", @must.url) unless @must.url.nil? || ["Have","Do"].include?(@must.category_name) %></p><br/><br/>

<div class="tags">
<p>
<b>Tags:</b>

<% @must.tag_list.each do |tag|%>
	<a href="<%= tags_path(tag) %>"><%= tag %></a>
<% end %>

</p>


<p>This must has <a><%= pluralize(@must.comments.count, 'comment') %></a></p>     
</div>     
</div> <!-- must_content -->

<div id="comments">
<%= render :partial => 'comments_list', :locals => { :must => @must} %>

<%= render :partial => 'comments', :locals => { :must => @must} %>


</div><!-- comments -->

</div><!-- right -->
</li>
	
		 
</ul>
<% if @must.listen? %>
  <% content_for :stylesheet do %>
    <%= stylesheet_link_tag 'audio_js/audio-js' %>
    <%= stylesheet_link_tag 'audio_js/skins/hu.css' %>
    <%= stylesheet_link_tag 'audio_js/skins/tube.css' %>
    <%= stylesheet_link_tag 'audio_js/skins/vim.css' %>
  <% end %>

  <% content_for :javascript do %>
    <%= javascript_include_tag "audio" %>
    <script type="text/javascript" charset="utf-8">
      $(function(){
        AudioJS.setup();
      })
    </script>
  <% end %>
<% end %>

app/views/musts/tags.html.erb
<h3>These are the Musts tagged as <%=h @tag %></h3>

<% unless @musts.blank? %>

<ul class="musts">
  <% @musts.each do |must| %>
  	<%= render :partial => "musts/must_item", :locals => {:must => must} %>
  <% end %>
</ul>

<%= will_paginate @musts %>

<% end %>

app/views/musts/user_musts.html.erb
<h3>These are the Musts posted by <%= @user.username %></h3>

<% unless @musts.blank? %>
	
<ul class="musts">
  <% @musts.each do |must| %>
  	<%= render :partial => "musts/must_item", :locals => {:must => must} %>
  <% end %>
</ul>
<%= will_paginate @musts %>
<% else %>
<h3>The user <%= @user.username %> hasn't written any Must yet</h3>
<% end %>